[conda]
# Enable the conda module, displaying the current conda environment.
format = "via [$symbol$environment]($style) "
# Optionally, you can specify a custom symbol to prefix the environment name.
symbol = "üêç "
# By default, the base environment is not shown. Set this to false to always display the environment name.
ignore_base = false
